[project]
name = "crypto-currency-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agent>=0.1.0",
    "streamlit>=1.47.1",
]
